# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bb04baf8dd27fb687d322579a2fa31ce4e0546304a8b544ec5cc27e77e992d1cdc7c3000ed9c3ebd0d4b8e00f99fc7290bef0bd30e830252e78bc139493f413

test:
  secret_key_base: 9e6d7a40192856466cf80aeb1805b616c1d3590e6e1f762f1b567f8e3dc43709c997d159fbbff222afc0bc42dcb98b1bd0c773e5b6326f7e1d50f8ebf40ca729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
